# Generated by Django 5.2.13 on 2026-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Images'), ('video', 'Vidéos'), ('both', 'Images et Vidéos')], default='image', max_length=10),
        ),
    ]
