# Generated by Django 5.2.13 on 2026-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0002_alter_projectmedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('both', 'Vidéo & Image')], default='image', max_length=10),
        ),
    ]
